stages:
- test

test:
  image: python:3.7.3
  script:
  - pip install -r requirements.txt
  - python -m unittest discover ./interviewer/ -v
  - coverage run --source=./interviewer -m unittest discover ./interviewer
  after_script:
  - ./buttons.sh
